const K="vp8";let db=load(),view="home",active=db.trips[0]?.id||null,tab="itinerary";
const $=id=>document.getElementById(id);
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2)}
function clean(s){return String(s||"").replace(/[\uD800-\uDFFF]/g,"")}
function esc(s){return clean(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function load(){try{return JSON.parse(localStorage.getItem(K))||seed()}catch(e){return seed()}}
function save(){localStorage.setItem(K,JSON.stringify(db))}
function seed(){return{trips:[{id:uid(),name:"Conil 2026",dates:"14 - 22 julio 2026",destination:"Sevilla, Conil y Cádiz",people:"Familia",hotel:"",hotelMap:"",image:"",summary:"Viaje a Sevilla y Conil.",sections:[]}],events:[],reservations:[],docs:[]}}
function trip(){return db.trips.find(t=>t.id===active)||db.trips[0]}
function norm(s){return clean(s).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim()}
function city(t=trip()){let b=((t?.destination||"")+" "+(t?.name||"")).toLowerCase();if(b.includes("bruselas"))return"Brussels Belgium";if(b.includes("conil")||b.includes("cadiz")||b.includes("cádiz"))return"Cádiz Spain";if(b.includes("sevilla"))return"Sevilla Spain";if(b.includes("londres"))return"London UK";if(b.includes("roma"))return"Rome Italy";return t?.destination||""}
function map(q,t=trip()){q=clean(q).replace(/[📍🎟🔗🗺️➡️➔]/g," ").trim();let c=city(t);if(c&&!q.toLowerCase().includes(c.toLowerCase().split(" ")[0]))q+=" "+c;return"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(q)}
function uniq(a,o,k="name"){let n=norm(o[k]||o.title||"");if(n&&!a.some(x=>norm(x[k]||x.title||"")===n))a.push(o)}
$("menu").onclick=()=>{side.classList.add("open");shade.classList.add("show")};$("x").onclick=$("shade").onclick=()=>{side.classList.remove("open");shade.classList.remove("show")};$("dark").onclick=()=>document.body.classList.toggle("dark");$("mx").onclick=closeModal;
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;side.classList.remove("open");shade.classList.remove("show");render()});
newTrip.onclick=()=>tripForm();newEvent.onclick=()=>eventForm();newRes.onclick=()=>resForm();
function modal(t,h){mt.textContent=t;mb.innerHTML=h;document.getElementById("modal").classList.add("show")}function closeModal(){document.getElementById("modal").classList.remove("show");mb.innerHTML=""}
function render(){document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("on",b.dataset.view===view));title.textContent={home:"Viajes & Planes",trips:"Viajes",events:"Eventos",reservations:"Reservas",docs:"Documentos"}[view]; if(view==="home")home(); if(view==="trips")trips(); if(view==="events")events(); if(view==="reservations")reservations(); if(view==="docs")docs()}
function row(t){return`<div class=item onclick="active='${t.id}';view='trips';render()"><div class=thumb>${t.image?`<img src="${esc(t.image)}">`:"✈️"}</div><div><b>${esc(t.name)}</b><br><span class=muted>${esc(t.dates)} · ${esc(t.destination)}</span></div><b>›</b></div>`}
function home(){app.innerHTML=`<section class=hero><div><h1>Viajes & Planes</h1><p>Viajes, entradas, reservas y documentos</p></div></section><div class=grid><div class=stat><span>${db.trips.length}</span>Viajes</div><div class=stat><span>${db.events.length}</span>Eventos</div><div class=stat><span>${db.reservations.length}</span>Reservas</div><div class=stat><span>${db.docs.length}</span>Docs</div></div><div class=card><h2>Próximos viajes</h2>${db.trips.map(row).join("")||"<p class=muted>Sin viajes.</p>"}</div><div class=card><h2>Eventos</h2>${db.events.map(e=>`<p>🎟️ <b>${esc(e.name)}</b><br><span class=muted>${esc(e.date)} · ${esc(e.place)}</span></p>`).join("")||"<p class=muted>Sin eventos.</p>"}</div>`}
function trips(){let t=trip(); if(!t){app.innerHTML=`<div class=card><button class=primary onclick=tripForm()>+ Nuevo viaje</button></div>`;return} app.innerHTML=`<section class=hero>${t.image?`<img src="${esc(t.image)}">`:""}<div><h1>${esc(t.name)}</h1><p>${esc(t.dates)}</p><p>${esc(t.destination)}</p></div></section><div class=tabs><button class="${tab==='itinerary'?'on':''}" onclick="tab='itinerary';render()">📅 Itinerario</button><button class="${tab==='food'?'on':''}" onclick="tab='food';render()">🍽 Comer</button><button class="${tab==='maps'?'on':''}" onclick="tab='maps';render()">📍 Mapas</button><button class="${tab==='logistics'?'on':''}" onclick="tab='logistics';render()">🚗 Logística</button><button class="${tab==='docs'?'on':''}" onclick="tab='docs';render()">📎 Docs</button></div><div class=card><h2>${esc(t.name)}</h2><span class=pill>${t.sections.length} notas</span><span class=pill>${places(t).length} mapas</span><span class=pill>${foods(t).length} restaurantes</span><p>${esc(t.summary)}</p><p><b>👥 Personas:</b> ${esc(t.people||"Sin indicar")}</p><p><b>🏨 Hotel:</b> ${esc(t.hotel||"Sin indicar")} ${(t.hotel||t.hotelMap)?`<br><a target=_blank href="${esc((t.hotelMap||t.hotel).startsWith("http")?t.hotelMap||t.hotel:map(t.hotelMap||t.hotel,t))}">Abrir hotel en Maps</a>`:""}</p><div class=actions><button class=secondary onclick="tripForm('${t.id}')">Editar</button><button class=secondary onclick=bulkForm()>Importar carpeta</button><button class=danger onclick="delTrip('${t.id}')">Eliminar</button></div></div>${tabContent(t)}`}
function tabContent(t){if(tab==="itinerary")return t.sections.length?t.sections.map(section).join(""):"<div class=empty>Importa una carpeta de notas.</div>";if(tab==="food")return foods(t).map(f=>`<div class=card><a target=_blank href="${esc(f.url)}">🍽 ${esc(f.name)}</a><p class=muted>${esc(f.address||"")}</p></div>`).join("")||"<div class=empty>Sin restaurantes.</div>";if(tab==="maps")return places(t).map(p=>`<div class=card><a target=_blank href="${esc(p.url)}">📍 ${esc(p.name)}</a><p class=muted>${esc(p.query)}</p></div>`).join("")||"<div class=empty>Sin mapas.</div>";if(tab==="logistics")return t.sections.filter(s=>s.type==="logistics").map(section).join("")||"<div class=empty>Sin logística.</div>";return `<div class=card><button class=primary onclick="docForm('${t.id}')">+ Documento</button>${db.docs.filter(d=>d.tripId===t.id).map(docCard).join("")||"<p class=muted>Sin documentos.</p>"}</div>`}
function section(s){return`<div class=acc><button onclick="this.parentElement.classList.toggle('open')">${icon(s.type)} <b>${esc(s.title)}</b> ⌄</button><div class=body>${s.times?.length?`<h3>⏰ Cronograma</h3>${s.times.map(x=>`<div class=place><b>${esc(x.time)}</b> ${esc(x.text)}</div>`).join("")}`:""}${s.places?.length?`<h3>📍 Mapas</h3>${s.places.map(p=>`<div class=place><a target=_blank href="${esc(p.url)}">📍 ${esc(p.name)}</a><p class=muted>${esc(p.query)}</p></div>`).join("")}`:""}${s.food?.length?`<h3>🍽 Restaurantes</h3>${s.food.map(f=>`<div class=place><a target=_blank href="${esc(f.url)}">🍽 ${esc(f.name)}</a><p class=muted>${esc(f.address||"")}</p></div>`).join("")}`:""}${s.notes?.length?`<h3>📝 Notas</h3>${s.notes.map(n=>`<p>• ${esc(n)}</p>`).join("")}`:""}<details><summary><b>Ver nota original</b></summary><p class=raw>${esc(s.raw)}</p></details></div></div>`}
function icon(x){return{day:"📅",food:"🍽",logistics:"🚗",reservation:"📧"}[x]||"📝"}
function tripForm(id=""){let t=id?db.trips.find(x=>x.id===id):{};modal(id?"Editar viaje":"Nuevo viaje",`<input id=f1 placeholder=Nombre value="${esc(t.name||"")}"><input id=f2 placeholder=Fechas value="${esc(t.dates||"")}"><input id=f3 placeholder=Destino value="${esc(t.destination||"")}"><input id=f4 placeholder=Personas value="${esc(t.people||"")}"><input id=f5 placeholder="Hotel / alojamiento" value="${esc(t.hotel||"")}"><input id=f6 placeholder="Dirección hotel o Maps" value="${esc(t.hotelMap||"")}"><input id=f7 placeholder="URL imagen portada" value="${esc(t.image||"")}"><textarea id=f8 placeholder=Resumen>${esc(t.summary||"")}</textarea><button class=primary onclick="saveTrip('${id}')">Guardar</button>`)}
function saveTrip(id=""){let t=id?db.trips.find(x=>x.id===id):{id:uid(),sections:[]};Object.assign(t,{name:f1.value,dates:f2.value,destination:f3.value,people:f4.value,hotel:f5.value,hotelMap:f6.value,image:f7.value,summary:f8.value});if(!id){db.trips.push(t);active=t.id}save();closeModal();render()}
function delTrip(id){if(confirm("¿Eliminar viaje?")){db.trips=db.trips.filter(t=>t.id!==id);active=db.trips[0]?.id||null;save();render()}}
function bulkForm(){modal("Importar carpeta de notas",`<p class=muted>La forma más fiable: pega varias notas separadas con líneas tipo:</p><div class=code>--- Martes 14 julio ---\ncontenido...\n\n--- Parkings Sevilla y Cáceres ---\ncontenido...</div><textarea id=bulk placeholder="Pega aquí todas las notas de la carpeta"></textarea><button class=primary onclick=bulkImport()>Importar carpeta</button>`)}
function bulkImport(){let t=trip(), chunks=split(bulk.value);chunks.forEach(c=>uniq(t.sections,parse(c.title,c.body,t),"title"));save();closeModal();tab="itinerary";render();alert("Carpeta importada")}
function split(raw){let parts=raw.split(/\n\s*---+\s*/).map(x=>x.trim()).filter(Boolean);if(parts.length>1)return parts.map(x=>{let l=x.split(/\n/);return{title:l.shift().replace(/---+$/,""),body:l.join("\n")}});return[{title:"Notas importadas",body:raw}]}
function parse(title,body,t){let s={id:uid(),title,raw:title+"\n"+body,type:type(title+" "+body),times:[],places:[],food:[],notes:[]},lastFood="";(s.raw.split(/\n/).map(x=>clean(x).trim()).filter(Boolean)).forEach(line=>{let c=line.replace(/^[-*•]\s*/,""),tm=c.match(/(\d{1,2}:\d{2})\s*[|–-]?\s*(.*)/);if(tm){s.times.push({time:tm[1],text:tm[2]});return}let num=c.match(/^\d+\.\s*(.+?)(\s*➔|\s*->|\s*Maps|$)/i);if(num){addPlace(s,num[1],num[1],t);return}let u=c.match(/https?:\/\/\S+/);if(u&&/maps|google/i.test(u[0])){addPlace(s,c.replace(u[0],"")||"Mapa",u[0],t);return}let dir=c.match(/Direcci[oó]n:\s*(.+?)(\s*\||$)/i);if(dir){lastFood?addFood(s,lastFood,dir[1],t):addPlace(s,"Dirección",dir[1],t);lastFood="";return}if(/FIN DE SIÈCLE|CHEZ LÉON|DELIRIUM|CASA JUAN|CUARTEL DEL MAR|CALIFA|4 ESTACIONES/i.test(c)){lastFood=c;addFood(s,c,c,t);return}if(!/Maps$/i.test(c)&&c!==title)s.notes.push(c)});return s}
function type(x){x=norm(x);if(/parking|distancias|transporte|tren|coche|aeropuerto|alojamiento/.test(x))return"logistics";if(/restaurante|comida|cena|casa juan|bar|califa/.test(x))return"food";return"day"}
function addPlace(s,n,q,t){uniq(s.places,{name:n.trim(),query:q.trim(),url:q.startsWith("http")?q:map(q,t)},"name")}function addFood(s,n,a,t){uniq(s.food,{name:n.trim(),address:a.trim(),url:map(a||n,t)},"name")}function places(t){let a=[];t.sections.forEach(s=>(s.places||[]).forEach(p=>uniq(a,p,"name")));return a}function foods(t){let a=[];t.sections.forEach(s=>(s.food||[]).forEach(f=>uniq(a,f,"name")));return a}
function events(){app.innerHTML=`<div class=card><h2>🎟️ Eventos y entradas</h2><button class=primary onclick=eventForm()>+ Nuevo evento</button></div>${db.events.map(e=>`<div class=card><h2>${esc(e.name)}</h2><p class=muted>${esc(e.date)} · ${esc(e.place)}</p>${e.link?`<a target=_blank href="${esc(e.link)}">Abrir entrada</a>`:""}<p>${esc(e.notes)}</p></div>`).join("")||"<div class=empty>Sin eventos.</div>"}`}
function eventForm(){modal("Nuevo evento",`<input id=e1 placeholder=Nombre><input id=e2 placeholder="Fecha y hora"><input id=e3 placeholder=Lugar><input id=e4 placeholder="Enlace entrada / PDF / Wallet"><textarea id=e5 placeholder="Notas o email"></textarea><button class=primary onclick=saveEvent()>Guardar</button>`)}function saveEvent(){db.events.push({id:uid(),name:e1.value,date:e2.value,place:e3.value,link:e4.value,notes:e5.value});save();closeModal();view="events";render()}
function reservations(){app.innerHTML=`<div class=card><h2>📧 Reservas</h2><button class=primary onclick=resForm()>+ Nueva reserva</button></div>${db.reservations.map(r=>`<div class=card><h2>${esc(r.name)}</h2><p class=muted>${esc(r.type)} · ${esc(r.date)}</p><p>${esc(r.locator)}</p>${r.address?`<a target=_blank href="${map(r.address)}">Abrir Maps</a>`:""}<details><summary>Email</summary><p class=raw>${esc(r.raw)}</p></details></div>`).join("")||"<div class=empty>Sin reservas.</div>"}`}
function resForm(){modal("Nueva reserva",`<select id=r1><option>Hotel</option><option>Vuelo</option><option>Tren</option><option>Restaurante</option><option>Entrada</option><option>Parking</option></select><input id=r2 placeholder=Nombre><input id=r3 placeholder=Fecha><input id=r4 placeholder=Localizador><input id=r5 placeholder=Dirección><textarea id=r6 placeholder="Pega email"></textarea><button class=primary onclick=saveRes()>Guardar</button>`)}function saveRes(){db.reservations.push({id:uid(),type:r1.value,name:r2.value,date:r3.value,locator:r4.value,address:r5.value,raw:r6.value});save();closeModal();view="reservations";render()}
function docs(){app.innerHTML=`<div class=card><h2>📂 Documentos</h2><button class=primary onclick=docForm()>+ Documento</button></div>${db.docs.map(docCard).join("")||"<div class=empty>Sin documentos.</div>"}`}
function docCard(d){return`<div class=card><h2>${esc(d.name)}</h2><p class=muted>${esc(d.type)}</p>${d.link?`<a target=_blank href="${esc(d.link)}">Abrir documento</a>`:""}<p>${esc(d.notes)}</p></div>`}function docForm(tripId=""){modal("Nuevo documento",`<input id=d1 placeholder=Nombre><select id=d2><option>PDF reserva</option><option>Entrada</option><option>Captura QR</option><option>Email</option><option>Otro</option></select><input id=d3 placeholder="Enlace al documento"><textarea id=d4 placeholder=Notas></textarea><button class=primary onclick="saveDoc('${tripId}')">Guardar</button>`)}function saveDoc(tripId){db.docs.push({id:uid(),tripId,name:d1.value,type:d2.value,link:d3.value,notes:d4.value});save();closeModal();render()}
render();
